version: '2'
services:
  discovery:
    image: coffeenet/coffeenet-discovery:latest
    ports:
      - "8761:8761"
    hostname: coffeenet-discovery.coffeenet
  ldap:
    image: coffeenet/ldap:latest
    ports:
      - "38900:389"
    hostname: coffeenet-ldap.coffeenet
