name: example
category: irgendwas
protocol: http
host: localhost
port: 9000
urlPath: /
actions: 
  - name: doStuff
    endpoint: /doStuff
    accept: JSON
    params:
      - name: someText
        type: TEXT
        options: 
          - hello
          - bye
      - name: anyNumber
        type: NUMBER
        limits:
          min: 1
          max: 99
  - name: doOtherStuff
    endpoint: /doOtherSTuff
    accept: XML
    params:
      - name: anEmail
        type: EMAIL
      - name: aDate
        type: DATE
        limits:
          min: 01.01.2014
          max: 01.06.2015
