security:
  user:
    password: password
authorizationServer:
  revokeUri: http://localhost:9999/uaa/oauth/revoke
spring:
  oauth2:
    client:
      accessTokenUri: http://localhost:9999/uaa/oauth/token
      userAuthorizationUri: http://localhost:9999/uaa/oauth/authorize
      clientId: selfservice
      clientSecret: selfservicesecret
    resource:
      userInfoUri: http://localhost:9999/uaa/user
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:selfservice;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: