security:
  user:
    password: password

spring:
  oauth2:
    sso:
      home:
        secure: false
        path: /,/**/*.html,/uaa/user
    client:
      accessTokenUri: http://localhost:9999/uaa/oauth/token
      userAuthorizationUri: http://localhost:9999/uaa/oauth/authorize
      clientId: acme
      clientSecret: acmesecret
    resource:
      userInfoUri: http://localhost:9999/uaa/user