security:
  user:
    password: password

spring:
  oauth2:
    client:
      accessTokenUri: http://euenos.synyx.coffee:9999/uaa/oauth/token
      userAuthorizationUri: http://euenos.synyx.coffee:9999/uaa/oauth/authorize
      clientId: acme
      clientSecret: acmesecret
    resource:
      userInfoUri: http://euenos.synyx.coffee:9999/uaa/user
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:selfservice;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: